<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 /*   'Noivos\Module'                        => __DIR__ . '/Module.php',
    'Noivos\Controller\IndexController' => __DIR__ . '/src/Noivos/Controller/IndexController.php',
    'NoivosTest\Framework\TestCase'        => __DIR__ . '/tests/Noivos/Framework/TestCase.php',
    'NoivosTest\SampleTest'                => __DIR__ . '/tests/Noivos/SampleTest.php',*/
);
