<?php echo $this->doctype(); ?>
<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("MyWedding") ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headMeta()->appendName('description', 'Site de Anuncios e Informações de Casamentos') ?>
        <?php echo $this->headMeta()->appendName('author', 'Daniel Chaves') ?>
        
        
