<section id="intro">
			<div class="container">
				<div class="row">
					<div class="span8 offset2 margin25">
						<div id="carousel_fade_intro" class="carousel slide carousel-fade">
							<div class="carousel-inner">
								<div class="active item">
									<h2>Bem Vindo ao MyWedding</h2>
								</div>
								<div class="inactive item">
									<h2>designed for portfolio, agency</h2>
								</div>
								<div class="inactive item">
									<h2>or app landing page.</h2>
								</div>
								<div class="inactive item">
									<h2>It's easy to customize</h2>
								</div>
								<div class="inactive item">
									<h2>to fit any brand.</h2>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="fadeInUp delay animated hidden-phone" id="more">
				<a href="#services-top" class="m-btn a-btn blue big icn-only"><i class="icon-sort-down icon-3x pull-left"></i></a>
			</div>
		</section>
	
	
	
	<!--start services header-->
		<section id="services-top">
	<!--start services-desktop header-->
			<section id="services-top-desktop" class="visible-desktop" data-stellar-background-ratio="0.6" data-stellar-vertical-offset="20">
				<h1 class="header">Services</h1>
				<p class="header">How awesome can it be?</p>
			</section>
	<!--start services-mobile header-->
			<section id="services-top-mobile" class="hidden-desktop">
				<h1 class="header">Services</h1>
				<p class="header">How awesome can it be?</p>
			</section>
		</section>
	<!--start services-->
		<section id="services">
			<div class="container">
				<div class="row divide">
					<div class="span12">
						<ul class="thumbnails">
							<li class="span4">
								<div class="thumbnail">
									<i class="icon-cogs"></i>
									<h4>Built with Bootstrap</h4>
									<span>HTML5 & CSS3 Valide Code</span>
									<p>Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers
									in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae.</p>
								</div>
							</li>
							<li class="span4">
								<div class="thumbnail">
									<i class="icon-eye-open"></i>
									<h4>Retina Ready</h4>
									<span>Ultra Sharp Graphics</span>
									<p>Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers
									in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae.</p>
								</div>
							</li>
							<li class="span4">
								<div class="thumbnail">
									<i class="icon-stethoscope"></i>
									<h4>Support</h4>
									<span>It's Free and Always Will Be</span>
									<p>Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers
									in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae.</p>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</section>
		<section id="hint1">
			<a href="http://fortawesome.github.com/Font-Awesome/" target="_blank"><strong>HEADS UP!</strong> Click here to check all <strong>249 icons</strong> that we integrated in this template</a>
		</section>
		
		
		
	